[package]
name = "space_shooter"
version = "0.1.0"
edition = "2021"
authors = ["Artur Gwo≈∫dziowski"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.8"
rand = "0.8"